# Generated by Django 5.2.7 on 2025-11-14 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livenotif", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this event is currently active/visible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "event_id",
                    models.CharField(
                        help_text="e.g., EVT-101, EVT-102",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(help_text="Name of the event", max_length=100),
                ),
                (
                    "event_description",
                    models.TextField(help_text="Detailed description of the event"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("normal", "Normal"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="ℹ️",
                        help_text="Emoji or icon for the event",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Event Type",
                "verbose_name_plural": "Event Types",
                "ordering": ["event_id"],
            },
        ),
        migrations.RemoveField(
            model_name="toastlog",
            name="toast",
        ),
        migrations.RemoveField(
            model_name="toastlog",
            name="user",
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ignored", "Ignored"), ("action", "Action Taken")],
                        help_text="User action: ignored or action taken",
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the action",
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="livenotif.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Log",
                "verbose_name_plural": "Event Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="livenotif.eventtype",
            ),
        ),
        migrations.DeleteModel(
            name="Toast",
        ),
        migrations.DeleteModel(
            name="ToastLog",
        ),
    ]
