# Generated by Django 5.2.7 on 2025-11-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livenotif", "0002_event_eventtype_remove_toastlog_toast_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventtype",
            name="icon",
        ),
    ]
