# Generated by Django 5.2.7 on 2025-12-09 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livenotif", "0003_remove_eventtype_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.CharField(
                default='system',
                help_text="Source of the event (e.g., 'alert_service', 'manual', 'sqs')",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
