# Generated by Django 5.2.7 on 2025-12-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livenotif", "0004_event_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="event_name",
            field=models.CharField(help_text="Name of the event", max_length=200),
        ),
    ]
