# Generated by Django 5.2.7 on 2025-12-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livenotif", "0005_alter_eventtype_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude coordinate of the event location",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude coordinate of the event location",
                max_digits=10,
                null=True,
            ),
        ),
    ]
