# Generated by Django 5.2.7 on 2025-12-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livenotif", "0006_event_latitude_event_longitude"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventLog",
        ),
    ]
