# Generated by Django 5.2.7 on 2025-12-03 07:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "access_key",
                    models.CharField(
                        db_index=True, editable=False, max_length=21, unique=True
                    ),
                ),
                (
                    "ttl",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiration date and time. Leave blank for no expiration.",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "API Authentication",
                "verbose_name_plural": "API Authentications",
                "db_table": "tmpl_api_auth",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_number", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("bus", "Bus"), ("truck", "Truck")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Model type",
                "verbose_name_plural": "Model types",
                "db_table": "dashboard_vehicletype",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255)),
                ("vendor_support_email", models.EmailField(max_length=254)),
                ("transvolt_contact_email", models.EmailField(max_length=254)),
                (
                    "transvolt_contact_person_mobile_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("vendor_support_site", models.URLField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specs",
                    models.JSONField(
                        help_text="Store specs as JSON, e.g. {'battery': '200kWh', 'range': '250km'}"
                    ),
                ),
                (
                    "vehicle_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification",
                        to="dashboard.modeltype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model specification",
                "verbose_name_plural": "Model specifications",
                "db_table": "dashboard_specification",
            },
        ),
        migrations.CreateModel(
            name="ModelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vehicles/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dashboard.modeltype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model image",
                "verbose_name_plural": "Model images",
                "db_table": "dashboard_vehicleimage",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msal_connected",
                    models.BooleanField(
                        default=False,
                        help_text="True if user was created/authenticated via Microsoft MSAL, False if manually created",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "vehicle_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("depot", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "battery_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "battery_capacity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "state_of_health",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="dashboard.modeltype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="modeltype",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_types",
                to="dashboard.vendor",
            ),
        ),
        migrations.CreateModel(
            name="ApiVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_auth",
                    models.ForeignKey(
                        help_text="The API authentication credential for this vendor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="dashboard.apiauth",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Vendor",
                "verbose_name_plural": "API Vendors",
                "db_table": "tmpl_api_vendors",
                "ordering": ["-created_at"],
                "unique_together": {("api_auth", "vendor_name")},
            },
        ),
        migrations.CreateModel(
            name="RevisionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Semantic version or tag",
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed notes or list of changes"),
                ),
                (
                    "created_by_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the user who created this revision (auto-filled)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="If false, this revision is hidden from public listing",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "effective_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this revision became effective",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this revision (auto-filled from request.user in admin)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revision_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["version"], name="dashboard_r_version_60444a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="dashboard_r_created_65ffb1_idx"
                    ),
                ],
            },
        ),
    ]
