# Generated by Django 4.2.20 on 2026-01-02 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_apiauth_ttl_to_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Role of the user at the time of action', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string')),
                ('session_id', models.CharField(blank=True, help_text='Session ID to group actions by session', max_length=255)),
                ('section', models.CharField(help_text='Application module or section', max_length=100)),
                ('action', models.CharField(help_text='Action performed by the user', max_length=255)),
                ('path', models.CharField(help_text='Request URL or frontend route', max_length=500)),
                ('method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10)),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP response status code (200, 404, 500, etc.)', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Request processing duration in milliseconds', null=True)),
                ('session_duration', models.IntegerField(blank=True, help_text='Total session duration in seconds at time of action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_action_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_action_user_id_155554_idx'), models.Index(fields=['section'], name='user_action_section_03d211_idx'), models.Index(fields=['created_at'], name='user_action_created_108070_idx'), models.Index(fields=['session_id'], name='user_action_session_c8e9fa_idx'), models.Index(fields=['response_status'], name='user_action_respons_9a4d57_idx')],
            },
        ),
    ]
