# Generated by Django 4.2.20 on 2026-01-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_page_project_role_userprojectrole_rolepage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['code'], 'verbose_name': 'RBAC: Page', 'verbose_name_plural': 'RBAC: Pages'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'RBAC: Project', 'verbose_name_plural': 'RBAC: Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={'ordering': ['project', 'page'], 'verbose_name': 'RBAC: Project-Page', 'verbose_name_plural': 'RBAC: Project-Pages'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['project', 'name'], 'verbose_name': 'RBAC: Role', 'verbose_name_plural': 'RBAC: Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepage',
            options={'ordering': ['project', 'role', 'page'], 'verbose_name': 'RBAC: Role-Page Permission', 'verbose_name_plural': 'RBAC: Role-Page Permissions'},
        ),
        migrations.AlterModelOptions(
            name='userprojectrole',
            options={'ordering': ['project', 'user'], 'verbose_name': 'RBAC: User-Project-Role', 'verbose_name_plural': 'RBAC: User-Project-Roles'},
        ),
    ]
