# Generated by Django 5.2.7 on 2026-01-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_page_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiauth",
            name="access_key",
            field=models.CharField(
                db_index=True, editable=False, max_length=21, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="ApiVendor",
        ),
    ]
