# Generated by Django 5.2.7 on 2026-02-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_apiauth_access_key_delete_apivendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="odometer_reading",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="state_of_health",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="mac_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="motor_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="project_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="seating_capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_registration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vendor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="dashboard.modeltype",
            ),
        ),
    ]
