# Generated by Django 5.2.7 on 2026-02-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_remove_vehicle_odometer_reading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="model",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
