# Generated by Django 5.2.7 on 2026-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_remove_vehicle_model_vehicle_model_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="length",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
