# Generated by Django 5.2.7 on 2026-02-27 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_vehicle_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="model_type",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model",
            field=models.ForeignKey(
                blank=True,
                help_text="Vehicle model type with specifications and images",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="dashboard.modeltype",
            ),
        ),
    ]
