# Generated by Django 5.2.7 on 2026-02-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_remove_vehicle_model_type_vehicle_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modelimage",
            old_name="vehicle_type",
            new_name="model_type",
        ),
        migrations.RenameField(
            model_name="modelspecification",
            old_name="vehicle_type",
            new_name="model_type",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="vendor",
        ),
    ]
