# Generated by Django 5.2.7 on 2026-03-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_rename_vehicle_type_to_model_type"),
    ]

    operations = [
        # Remove all unique_together constraints first
        migrations.AlterUniqueTogether(
            name="projectpage",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="rolepage",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="userprojectrole",
            unique_together=None,
        ),
        # Then remove fields
        migrations.RemoveField(
            model_name="rolepage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="projectpage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="projectpage",
            name="project",
        ),
        migrations.RemoveField(
            model_name="userprojectrole",
            name="project",
        ),
        migrations.RemoveField(
            model_name="role",
            name="project",
        ),
        migrations.RemoveField(
            model_name="rolepage",
            name="project",
        ),
        migrations.RemoveField(
            model_name="rolepage",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userprojectrole",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userprojectrole",
            name="user",
        ),
        # Finally delete models
        migrations.DeleteModel(
            name="Page",
        ),
        migrations.DeleteModel(
            name="ProjectPage",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="RolePage",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="UserProjectRole",
        ),
    ]
