# Generated by Django 5.2.7 on 2026-03-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_remove_rolepage_page_remove_projectpage_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "RBAC: Page",
                "verbose_name_plural": "RBAC: Pages",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "RBAC: Project",
                "verbose_name_plural": "RBAC: Projects",
                "ordering": ["name"],
            },
        ),
    ]
