# Generated by Django 5.2.7 on 2026-03-18 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("dashboard", "0013_page_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Assign user to a group for access control",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="auth.group",
            ),
        ),
        migrations.CreateModel(
            name="GroupAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional access configuration (optional)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_config",
                        to="auth.group",
                    ),
                ),
                (
                    "pages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pages this group has access to",
                        related_name="group_accesses",
                        to="dashboard.page",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Projects this group has access to",
                        related_name="group_accesses",
                        to="dashboard.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Access",
                "verbose_name_plural": "Group Access",
            },
        ),
    ]
