# Generated by Django 5.2.7 on 2026-03-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_userprofile_group_groupaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="project",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="section",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
