# Generated by Django 4.2.20 on 2025-11-12 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_no", models.TextField()),
                ("geofence_name", models.TextField(null=True)),
                ("gps_location", models.TextField(null=True)),
                ("lat", models.FloatField(null=True)),
                ("lon", models.FloatField(null=True)),
                ("soc", models.IntegerField(null=True)),
                ("alert_type", models.TextField()),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_no", models.TextField(null=True)),
                ("last_lat", models.FloatField(null=True)),
                ("last_lon", models.FloatField(null=True)),
                ("last_soc", models.IntegerField(null=True)),
                ("last_status", models.TextField(null=True)),
                ("last_connected", models.DateTimeField(null=True)),
                ("current_geofence", models.TextField(null=True)),
                ("inside_since", models.DateTimeField(null=True)),
                ("outside_since", models.DateTimeField(null=True)),
                ("stop_start_ts", models.DateTimeField(null=True)),
                ("charging_start_ts", models.DateTimeField(null=True)),
                ("last_departure_ts", models.DateTimeField(null=True)),
                ("last_departure_geofence", models.TextField(null=True)),
                ("last_alert_ts", models.DateTimeField(null=True)),
            ],
        ),
    ]
