# Generated by Django 4.2.20 on 2025-11-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livetracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclealert",
            name="driver_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="vehiclealert",
            name="vehicle_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="vehiclestate",
            name="driver_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="vehiclestate",
            name="vehicle_id",
            field=models.TextField(null=True),
        ),
    ]
