# Generated by Django 5.2 on 2025-11-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "livetracker",
            "0002_vehiclealert_driver_name_vehiclealert_vehicle_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclealert",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                help_text="Priority of the alert",
                max_length=10,
            ),
        ),
    ]
