# Generated by Django 5.2.7 on 2025-12-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livetracker", "0003_vehiclealert_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclestate",
            name="last_alert_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
