# Generated by Django 5.2.7 on 2025-12-09 03:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livetracker", "0004_vehiclestate_last_alert_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Auto-incrementing primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the alert",
                        unique=True,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        help_text="Event ID from livenotif system (e.g., EVT-001)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("closed", "Closed"),
                            ("acknowledged", "Acknowledged"),
                            ("action_taken", "Action Taken"),
                        ],
                        help_text="Type of action taken on the alert",
                        max_length=20,
                    ),
                ),
                (
                    "action_taken_by",
                    models.CharField(
                        help_text="Username or identifier of who took the action (auto-filled from request.user)",
                        max_length=150,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or comments about the action",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the action was taken",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
            ],
            options={
                "db_table": "livetracker_alert_action",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["alert_id"], name="livetracker_alert_i_9f635a_idx"
                    ),
                    models.Index(
                        fields=["event_id"], name="livetracker_event_i_4e8a92_idx"
                    ),
                    models.Index(
                        fields=["action_taken_by", "-created_at"],
                        name="livetracker_action__2c06fb_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="livetracker_created_ebaca8_idx"
                    ),
                ],
            },
        ),
    ]
