# Generated by Django 4.2.20 on 2025-12-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livetracker', '0006_livetrackerfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetrackerfeedback',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('working', 'Working on it'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
