# Generated by Django 4.2.20 on 2025-12-26 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livetracker', '0007_alter_livetrackerfeedback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrackerAlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=100)),
                ('alert_type', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('action_type', models.CharField(choices=[('ack', 'Acknowledged'), ('action', 'Action Taken')], max_length=20)),
                ('action_note', models.TextField(blank=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Alert User Action',
                'verbose_name_plural': 'Live Alert User Actions',
                'db_table': 'livetracker_live_alert_action',
                'ordering': ['-action_at'],
                'indexes': [models.Index(fields=['alert_id'], name='live_alert_alertid_idx'), models.Index(fields=['user'], name='live_alert_user_idx'), models.Index(fields=['-action_at'], name='live_alert_actionat_idx'), models.Index(fields=['vehicle_no'], name='live_alert_vehicle_idx')],
                'unique_together': {('alert_id', 'user', 'action_type')},
            },
        ),
    ]
