# Generated by Django 4.2.20 on 2026-01-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livetracker', '0009_delete_alertaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livetrackerfeedback',
            table='feedback',
        ),
    ]
