# Generated by Django 4.2.20 on 2026-01-09 03:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livetracker', '0010_alter_livetrackerfeedback_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiveTrackerFeedback',
            new_name='Feedback',
        ),
    ]
