# Generated by Django 5.2.7 on 2026-01-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livetracker", "0011_rename_livetrackerfeedback_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeBoxDailyAvgDelay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("avg_delay_minutes", models.IntegerField(default=0)),
                ("vehicle_count", models.IntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
