# Generated by Django 5.2.7 on 2026-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livetracker", "0013_geofence"),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetTrendDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("spv", models.CharField(db_index=True, max_length=50)),
                ("avg_distance_km", models.FloatField(null=True)),
                ("avg_energy_kwh", models.FloatField(null=True)),
                ("avg_efficiency_kwh_per_km", models.FloatField(null=True)),
                ("vehicle_count", models.IntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("date", "spv")},
            },
        ),
    ]
