# Generated by Django 5.2.7 on 2026-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livetracker", "0014_fleet_trend_daily"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fleettrenddaily",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fleettrenddaily",
            name="vehicle_no",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="fleettrenddaily",
            unique_together={("date", "spv", "vehicle_no")},
        ),
    ]
