# Generated by Django 5.2.7 on 2026-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livetracker", "0015_fleet_trend_vehicle_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclealert",
            name="spv",
            field=models.CharField(
                blank=True,
                help_text="SPV/project identifier (e.g., 'ULTRATECH', 'MBMT')",
                max_length=50,
                null=True,
            ),
        ),
    ]
