# Generated by Django 5.2.7 on 2026-03-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globaltracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='geofencezone',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='route',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='route',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle',
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicleposition',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='GeofenceZone',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehiclePosition',
        ),
    ]
