# Generated by Django 5.2.7 on 2025-12-05 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField(db_index=True, verbose_name="Log Date")),
                (
                    "driver_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Driver ID"
                    ),
                ),
                (
                    "lr",
                    models.CharField(
                        blank=True,
                        help_text="Lorry Receipt Number",
                        max_length=100,
                        null=True,
                        verbose_name="LR",
                    ),
                ),
                (
                    "from_location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="From"
                    ),
                ),
                (
                    "trailer_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Trailer No."
                    ),
                ),
                (
                    "horse_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Horse No."
                    ),
                ),
                (
                    "trailer_oem",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Trailer OEM",
                    ),
                ),
                (
                    "delivery_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Delivery No.",
                    ),
                ),
                (
                    "tonnage_load",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="in tonnes",
                        max_digits=10,
                        null=True,
                        verbose_name="Tonnage Load",
                    ),
                ),
                (
                    "toll_paid_manawar_jhulwania",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="in rupees",
                        max_digits=10,
                        null=True,
                        verbose_name="Toll Paid (Manawar to Jhulwania)",
                    ),
                ),
                (
                    "driver_id_jhulwania",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Driver ID (Jhulwania)",
                    ),
                ),
                (
                    "trailer_no_jhulwania",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Trailer No. (Jhulwania)",
                    ),
                ),
                (
                    "horse_no_jhulwania",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Horse No. (Jhulwania)",
                    ),
                ),
                (
                    "toll_paid_jhulwania_dhule",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="in rupees",
                        max_digits=10,
                        null=True,
                        verbose_name="Toll Paid (Jhulwania to Dhule)",
                    ),
                ),
                (
                    "tonnage_unload",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="in tonnes",
                        max_digits=10,
                        null=True,
                        verbose_name="Tonnage Unload",
                    ),
                ),
                (
                    "maintenance",
                    models.TextField(
                        blank=True,
                        help_text="Maintenance notes or issues",
                        null=True,
                        verbose_name="Maintenance",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Log",
                "verbose_name_plural": "Daily Logs",
                "db_table": "mis_daily_log",
                "ordering": ["-log_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-log_date"], name="mis_daily_l_log_dat_843d50_idx"
                    ),
                    models.Index(
                        fields=["horse_no"], name="mis_daily_l_horse_n_bb98cd_idx"
                    ),
                    models.Index(
                        fields=["trailer_no"], name="mis_daily_l_trailer_000e31_idx"
                    ),
                ],
            },
        ),
    ]
