# Generated by Django 5.2.7 on 2025-12-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="all_station_total_charging_hours",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="All Station Total Charging Hours (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="closing_km_previous_trip",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Closing KM (Previous Trip)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="closing_soc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Closing SOC (%)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="closing_soc_dhule",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Closing SOC Dhule (%)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="closing_soc_jhulwania",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Closing SOC Jhulwania (%)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="closing_soc_return",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Closing SOC Return (%)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhar_charging_duration",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Dhar Charging Duration (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhar_charging_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Dhar Charging End Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhar_charging_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dhar Charging Start Date"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhar_charging_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Dhar Charging Start Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhar_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Dhar KWH",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhar_reach_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dhar Reach Date & Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhule_charging_duration",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Dhule Charging Duration (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhule_charging_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Dhule Charging End Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhule_charging_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dhule Charging Start Date"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhule_charging_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Dhule Charging Start Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhule_entry_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dhule Entry Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhule_idle_time",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Dhule Idle Time (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="dhule_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Dhule KWH",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="direction",
            field=models.CharField(
                blank=True,
                help_text="dhar_to_dhule or dhule_to_dhar",
                max_length=50,
                null=True,
                verbose_name="Direction",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="end_soc_dhule",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="End SOC Dhule (%)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="end_soc_jhulwania",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="End SOC Jhulwania (%)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="end_soc_previous_trip",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="End SOC (Previous Trip %)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="jhulwania_charging_duration",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Jhulwania Charging Duration (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="jhulwania_charging_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Jhulwania Charging End Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="jhulwania_charging_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Jhulwania Charging Start Date"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="jhulwania_charging_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Jhulwania Charging Start Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="jhulwania_entry_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Jhulwania Entry Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="jhulwania_exit_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Jhulwania Exit Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="jhulwania_idle_time",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Jhulwania Idle Time (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="jhulwania_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Jhulwania KWH",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_dhule_charging_duration",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Return Dhule Charging Duration (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_dhule_charging_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Return Dhule Charging End Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_dhule_charging_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Return Dhule Charging Start Date"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_dhule_charging_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Return Dhule Charging Start Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_dhule_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Return Dhule KWH",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_jhulwania_charging_duration",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Return Jhulwania Charging Duration (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_jhulwania_charging_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Return Jhulwania Charging End Time"
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_jhulwania_charging_start_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Return Jhulwania Charging Start Date",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_jhulwania_charging_start_time",
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name="Return Jhulwania Charging Start Time",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="return_jhulwania_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Return Jhulwania KWH",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="start_soc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Start SOC (%)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="start_soc_dhule",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Start SOC Dhule (%)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="start_soc_jhulwania",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Start SOC Jhulwania (%)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="telemetry_calculated",
            field=models.BooleanField(
                default=False,
                help_text="Whether calculated fields were auto-populated",
                verbose_name="Telemetry Calculated",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="telemetry_calculation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When fields were calculated",
                null=True,
                verbose_name="Telemetry Calculation Date",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="telemetry_data_points",
            field=models.IntegerField(
                blank=True,
                help_text="Number of telemetry records used",
                null=True,
                verbose_name="Telemetry Data Points",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="to_destination",
            field=models.CharField(
                blank=True,
                help_text="Destination: Dhule or Dhar (Return)",
                max_length=100,
                null=True,
                verbose_name="To",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="total_kwh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total KWH",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="total_trip_time",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Total Trip Time (HH:MM)",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="trip_closed_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Trip Closed KM",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="trip_start_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Trip Start KM",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="vehicle_out_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vehicle Out Time (Dhar)"
            ),
        ),
    ]
