# Generated by Django 5.2.7 on 2025-12-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0002_dailylog_all_station_total_charging_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='all_station_total_charging_hours',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='closing_km_previous_trip',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='closing_soc',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='closing_soc_dhule',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='closing_soc_jhulwania',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='closing_soc_return',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhar_charging_duration',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhar_charging_end_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhar_charging_start_date',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhar_charging_start_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhar_kwh',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhar_reach_datetime',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhule_charging_duration',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhule_charging_end_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhule_charging_start_date',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhule_charging_start_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhule_entry_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhule_idle_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='dhule_kwh',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='end_soc_dhule',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='end_soc_jhulwania',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='end_soc_previous_trip',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='jhulwania_charging_duration',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='jhulwania_charging_end_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='jhulwania_charging_start_date',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='jhulwania_charging_start_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='jhulwania_entry_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='jhulwania_exit_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='jhulwania_idle_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='jhulwania_kwh',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_dhule_charging_duration',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_dhule_charging_end_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_dhule_charging_start_date',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_dhule_charging_start_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_dhule_kwh',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_jhulwania_charging_duration',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_jhulwania_charging_end_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_jhulwania_charging_start_date',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_jhulwania_charging_start_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='return_jhulwania_kwh',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='start_soc',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='start_soc_dhule',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='start_soc_jhulwania',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='telemetry_calculated',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='telemetry_calculation_date',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='telemetry_data_points',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='to_destination',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='total_kwh',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='total_trip_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='trip_closed_km',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='trip_start_km',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='vehicle_out_time',
        ),
        migrations.CreateModel(
            name='CalculatedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(db_index=True, max_length=50, verbose_name='Vehicle Number')),
                ('log_date', models.DateField(db_index=True, verbose_name='Trip Date')),
                ('manawar_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Manawar In Time')),
                ('manawar_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Manawar Out Time')),
                ('start_soc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Start SOC (%)')),
                ('trip_start_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Trip Start KM')),
                ('closing_soc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Closing SOC After Charging (%)')),
                ('dhar_charging_start_date', models.DateField(blank=True, null=True, verbose_name='Dhar Charging Start Date')),
                ('dhar_charging_start_time', models.TimeField(blank=True, null=True, verbose_name='Dhar Charging Start Time')),
                ('dhar_charging_end_time', models.TimeField(blank=True, null=True, verbose_name='Dhar Charging End Time')),
                ('dhar_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KWH (Dhar)')),
                ('dhar_charging_duration', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dhar Charging Time (HH:MM)')),
                ('manawar_loading_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='Manawar Loading Time (HH:MM)')),
                ('manawar_julwaniya_stoppage', models.CharField(blank=True, max_length=10, null=True, verbose_name='Stoppage Manawar-Julwaniya (HH:MM)')),
                ('manawar_julwaniya_moving', models.CharField(blank=True, max_length=10, null=True, verbose_name='Moving Time Manawar-Julwaniya (HH:MM)')),
                ('manawar_julwaniya_total', models.CharField(blank=True, max_length=10, null=True, verbose_name='Total Time Manawar-Julwaniya (HH:MM)')),
                ('julwaniya_entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Julwaniya Entry Time')),
                ('julwaniya_exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Julwaniya Exit Time')),
                ('closing_km_julwaniya', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Closing KM Julwaniya')),
                ('end_soc_julwaniya', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='End SOC Julwaniya (%)')),
                ('start_soc_julwaniya', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Start SOC Julwaniya (%)')),
                ('closing_soc_julwaniya', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Closing SOC Julwaniya (%)')),
                ('julwaniya_charging_start_date', models.DateField(blank=True, null=True, verbose_name='Julwaniya Charging Start Date')),
                ('julwaniya_charging_start_time', models.TimeField(blank=True, null=True, verbose_name='Julwaniya Charging Start Time')),
                ('julwaniya_charging_end_time', models.TimeField(blank=True, null=True, verbose_name='Julwaniya Charging End Time')),
                ('julwaniya_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KWH Julwaniya')),
                ('julwaniya_charging_duration', models.CharField(blank=True, max_length=10, null=True, verbose_name='Julwaniya Charging Time (HH:MM)')),
                ('idle_time_julwaniya', models.CharField(blank=True, max_length=10, null=True, verbose_name='Idle Time Julwaniya (HH:MM)')),
                ('start_km_after_julwaniya', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Start KM After Julwaniya')),
                ('julwaniya_dhule_stoppage', models.CharField(blank=True, max_length=10, null=True, verbose_name='Stoppage Julwaniya-Dhule (HH:MM)')),
                ('dhule_entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Dhule Entry Time')),
                ('dhule_exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Dhule Exit Time')),
                ('closing_km_dhule', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Closing KM Dhule')),
                ('end_soc_dhule', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='End SOC Dhule (%)')),
                ('start_soc_dhule', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Start SOC Dhule (%)')),
                ('closing_soc_dhule', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Closing SOC Dhule (%)')),
                ('dhule_charging_start_date', models.DateField(blank=True, null=True, verbose_name='Dhule Charging Start Date')),
                ('dhule_charging_start_time', models.TimeField(blank=True, null=True, verbose_name='Dhule Charging Start Time')),
                ('dhule_charging_end_time', models.TimeField(blank=True, null=True, verbose_name='Dhule Charging End Time')),
                ('dhule_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KWH Dhule')),
                ('dhule_charging_duration', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dhule Charging Time (HH:MM)')),
                ('idle_time_dhule', models.CharField(blank=True, max_length=10, null=True, verbose_name='Idle Time Dhule (HH:MM)')),
                ('km_return_julwaniya', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KM Return Julwaniya')),
                ('end_soc_return', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='End SOC Return (%)')),
                ('start_soc_return', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Start SOC Return (%)')),
                ('closing_soc_return', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Closing SOC Return (%)')),
                ('julwaniya_entry_time_return', models.DateTimeField(blank=True, null=True, verbose_name='Julwaniya Entry Time (Return)')),
                ('julwaniya_exit_time_return', models.DateTimeField(blank=True, null=True, verbose_name='Julwaniya Exit Time (Return)')),
                ('julwaniya_return_charging_start_date', models.DateField(blank=True, null=True, verbose_name='Return Charging Start Date')),
                ('julwaniya_return_charging_start_time', models.TimeField(blank=True, null=True, verbose_name='Return Charging Start Time')),
                ('julwaniya_return_charging_end_time', models.TimeField(blank=True, null=True, verbose_name='Return Charging End Time')),
                ('julwaniya_return_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KWH Return')),
                ('julwaniya_return_charging_duration', models.CharField(blank=True, max_length=10, null=True, verbose_name='Return Charging Duration (HH:MM)')),
                ('dhar_reach_time', models.DateTimeField(blank=True, null=True, verbose_name='Dhar Reach Time')),
                ('trip_closed_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Trip Closed KM')),
                ('all_station_total_charging_hours', models.CharField(blank=True, max_length=10, null=True, verbose_name='Total Charging Hours (HH:MM)')),
                ('vehicle_total_trip_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='Total Trip Time (HH:MM)')),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Total Distance (km)')),
                ('total_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Total KWH')),
                ('efficiency_kwh_per_km', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Efficiency (kWh/km)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculated At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('raw_data', models.TextField(blank=True, null=True, verbose_name='Raw Calculation Data')),
            ],
            options={
                'verbose_name': 'Calculated Trip',
                'verbose_name_plural': 'Calculated Trips',
                'db_table': 'mis_calculated_trip',
                'ordering': ['-log_date', '-manawar_in_time'],
                'indexes': [models.Index(fields=['-log_date'], name='mis_calcula_log_dat_8e7dc7_idx'), models.Index(fields=['vehicle_no'], name='mis_calcula_vehicle_cad2fb_idx'), models.Index(fields=['vehicle_no', 'log_date'], name='mis_calcula_vehicle_b271cd_idx')],
                'unique_together': {('vehicle_no', 'manawar_in_time')},
            },
        ),
    ]
