# Generated by Django 5.2.7 on 2025-12-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0003_remove_dailylog_all_station_total_charging_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedtrip',
            name='total_trip_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Total Trip KM'),
        ),
    ]
