# Generated by Django 5.2.7 on 2026-01-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0004_calculatedtrip_total_trip_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatedtrip",
            name="dhar_reach_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dhar Reach Date"
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="vehicle_out_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vehicle Out Time"
            ),
        ),
    ]
