# Generated by Django 5.2.7 on 2026-01-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0005_calculatedtrip_dhar_reach_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='closing_soc_return',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='end_soc_return',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='julwaniya_entry_time_return',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='julwaniya_exit_time_return',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='julwaniya_return_charging_duration',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='julwaniya_return_charging_end_time',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='julwaniya_return_charging_start_date',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='julwaniya_return_charging_start_time',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='julwaniya_return_kwh',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='km_return_julwaniya',
        ),
        migrations.RemoveField(
            model_name='calculatedtrip',
            name='start_soc_return',
        ),
    ]
