# Generated by Django 5.2.7 on 2026-01-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0006_remove_calculatedtrip_closing_soc_return_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecomputeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the month being recomputed"
                    ),
                ),
                (
                    "target_day",
                    models.DateField(help_text="Target day (typically yesterday)"),
                ),
                ("lookback_days", models.IntegerField(default=5)),
                (
                    "vehicle_no",
                    models.CharField(
                        blank=True,
                        help_text="Optional vehicle filter",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("raw_rows", models.IntegerField(default=0)),
                ("telemetry_rows", models.IntegerField(default=0)),
                ("calculated_trips", models.IntegerField(default=0)),
                ("deleted_count", models.IntegerField(default=0)),
                ("saved_count", models.IntegerField(default=0)),
                (
                    "duration_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "mis_recompute_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="mis_recompu_started_f79db6_idx"
                    ),
                    models.Index(fields=["month"], name="mis_recompu_month_07c9b5_idx"),
                    models.Index(
                        fields=["status"], name="mis_recompu_status_665643_idx"
                    ),
                ],
            },
        ),
    ]
