# Generated by Django 5.2.7 on 2026-03-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0008_vehicletripstate"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="vehicletripstate",
            new_name="mis_vehicle_vehicle_7ba6c5_idx",
            old_name="mis_vehicletripstate_vehicle_date_idx",
        ),
        migrations.AlterField(
            model_name="vehicletripstate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
