# Generated by Django 5.2.7 on 2026-04-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mis",
            "0009_rename_mis_vehicletripstate_vehicle_date_idx_mis_vehicle_vehicle_7ba6c5_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatedtrip",
            name="charging_area_move_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Charging Area Move Time (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="charging_area_stop_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Charging Area Stop Time (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="charging_area_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Charging Area Total Time (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="gained_soc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Gained SOC (%)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="loading_stop_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Loading Stop Time (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="plant_area_move_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Plant Area Move Time (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="plant_area_stop_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Plant Area Stop Time (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="plant_area_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Plant Area Time (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="plugged_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Plugged (Charging) Time (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="trip_duration_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Trip Duration (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="unloading_stop_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Unloading Stop Time (s)",
            ),
        ),
        migrations.AddField(
            model_name="calculatedtrip",
            name="unplanned_stoppage_time_s",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=12,
                null=True,
                verbose_name="Unplanned Stoppage Time (s)",
            ),
        ),
        migrations.CreateModel(
            name="TripPerformanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        db_index=True, max_length=7, verbose_name="Month (YYYY-MM)"
                    ),
                ),
                (
                    "vehicle_no",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Vehicle Number"
                    ),
                ),
                (
                    "trip_count",
                    models.IntegerField(default=0, verbose_name="Trip Count"),
                ),
                (
                    "avg_trip_duration_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Trip Duration (s)",
                    ),
                ),
                (
                    "avg_efficiency_kwh_per_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Avg Efficiency (kWh/km)",
                    ),
                ),
                (
                    "avg_plant_area_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Plant Area Time (s)",
                    ),
                ),
                (
                    "avg_plant_area_stop_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Plant Area Stop Time (s)",
                    ),
                ),
                (
                    "avg_plant_area_move_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Plant Area Move Time (s)",
                    ),
                ),
                (
                    "avg_loading_stop_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Loading Stop Time (s)",
                    ),
                ),
                (
                    "avg_unloading_stop_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Unloading Stop Time (s)",
                    ),
                ),
                (
                    "avg_charging_area_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Charging Area Time (s)",
                    ),
                ),
                (
                    "avg_plugged_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Plugged Time (s)",
                    ),
                ),
                (
                    "avg_charging_area_stop_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Charging Area Stop Time (s)",
                    ),
                ),
                (
                    "avg_charging_area_move_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Charging Area Move Time (s)",
                    ),
                ),
                (
                    "avg_unplanned_stoppage_time_s",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=12,
                        null=True,
                        verbose_name="Avg Unplanned Stoppage Time (s)",
                    ),
                ),
                (
                    "avg_gained_soc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Avg Gained SOC (%)",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Computed At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Performance Summary",
                "verbose_name_plural": "Trip Performance Summaries",
                "db_table": "mis_trip_performance_summary",
                "ordering": ["month", "vehicle_no"],
                "indexes": [
                    models.Index(
                        fields=["month", "vehicle_no"],
                        name="mis_trip_pe_month_781b54_idx",
                    )
                ],
                "unique_together": {("month", "vehicle_no")},
            },
        ),
    ]
