# Generated by Django 5.2.7 on 2026-04-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0010_trip_performance_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullPipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Range Start Date")),
                ("end_date", models.DateField(verbose_name="Range End Date")),
                (
                    "vehicle_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Vehicle Filter",
                    ),
                ),
                (
                    "trips_calculated",
                    models.IntegerField(default=0, verbose_name="Trips Calculated"),
                ),
                (
                    "trips_saved",
                    models.IntegerField(default=0, verbose_name="Trips Saved to DB"),
                ),
                (
                    "summary_months_updated",
                    models.IntegerField(
                        default=0, verbose_name="Summary Months Updated"
                    ),
                ),
                (
                    "summary_vehicles_updated",
                    models.IntegerField(
                        default=0, verbose_name="Summary Vehicles Updated"
                    ),
                ),
                (
                    "duration_seconds",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Duration (s)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ended At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "log",
                    models.TextField(blank=True, null=True, verbose_name="Run Log"),
                ),
            ],
            options={
                "verbose_name": "Full Pipeline Run",
                "verbose_name_plural": "Full Pipeline Runs",
                "db_table": "mis_full_pipeline_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="mis_full_pi_started_4159a6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="mis_full_pi_status_0b27ce_idx"
                    ),
                ],
            },
        ),
    ]
