# Generated by Django 5.2.7
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mis', '0012_add_plant_specific_fields'),
    ]

    operations = [
        # Phase-specific delay metrics for trend graph optimization
        migrations.AddField(
            model_name='calculatedtrip',
            name='manawar_loading_delay_s',
            field=models.IntegerField(blank=True, help_text='Delay beyond SLA for loading operations', null=True, verbose_name='Manawar Loading Delay (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='dhule_unloading_delay_s', 
            field=models.IntegerField(blank=True, help_text='Delay beyond SLA for unloading operations', null=True, verbose_name='Dhule Unloading Delay (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='manawar_charging_delay_s',
            field=models.IntegerField(blank=True, help_text='Delay beyond SLA for charging', null=True, verbose_name='Manawar Charging Delay (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='dhule_charging_delay_s',
            field=models.IntegerField(blank=True, help_text='Delay beyond SLA for charging', null=True, verbose_name='Dhule Charging Delay (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='jhulwania_charging_delay_s',
            field=models.IntegerField(blank=True, help_text='Delay beyond SLA for charging', null=True, verbose_name='Jhulwania Charging Delay (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='maha_border_delay_s',
            field=models.IntegerField(blank=True, help_text='Delay beyond SLA at border crossing', null=True, verbose_name='MH Border Delay (s)'),
        ),
        
        # Aggregate delay fields for fast trend calculation
        migrations.AddField(
            model_name='calculatedtrip',
            name='total_delay_s',
            field=models.IntegerField(blank=True, help_text='Sum of all phase delays beyond SLA', null=True, verbose_name='Total Delay (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='ultratech_delay_s',
            field=models.IntegerField(blank=True, help_text='Delay at Ultratech facilities (Manawar + Dhule)', null=True, verbose_name='Ultratech Delay (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='driver_delay_s',
            field=models.IntegerField(blank=True, help_text='Delay during transit and other phases', null=True, verbose_name='Driver/Transit Delay (s)'),
        ),
        
        # Transit duration metrics for comprehensive analytics
        migrations.AddField(
            model_name='calculatedtrip',
            name='manawar_to_jhulwania_duration_s',
            field=models.IntegerField(blank=True, null=True, verbose_name='Manawar→Jhulwania Duration (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='jhulwania_to_dhule_duration_s',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jhulwania→Dhule Duration (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='dhule_to_manawar_duration_s', 
            field=models.IntegerField(blank=True, null=True, verbose_name='Dhule→Manawar Duration (s)'),
        ),
        migrations.AddField(
            model_name='calculatedtrip',
            name='total_drive_time_s',
            field=models.IntegerField(blank=True, help_text='Sum of all transit phases', null=True, verbose_name='Total Drive Time (s)'),
        ),
        
        # Add database indexes for fast trend queries
        migrations.AddIndex(
            model_name='calculatedtrip',
            index=models.Index(fields=['log_date', 'total_delay_s'], name='mis_calc_trip_date_delay_idx'),
        ),
        migrations.AddIndex(
            model_name='calculatedtrip', 
            index=models.Index(fields=['log_date', 'vehicle_no'], name='mis_calc_trip_date_vehicle_idx'),
        ),
    ]