# Generated by Django 4.2.20 on 2025-11-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriverMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("employee_name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Driver Master",
                "verbose_name_plural": "Driver Masters",
                "db_table": "driver_master",
            },
        ),
        migrations.CreateModel(
            name="HorseTrolleyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horse_number", models.CharField(db_index=True, max_length=50)),
                (
                    "trolley_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("driver_code", models.CharField(db_index=True, max_length=50)),
                ("driver_name", models.CharField(max_length=200)),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Horse Trolley Assignment",
                "verbose_name_plural": "Horse Trolley Assignments",
                "db_table": "horse_trolley_assignment",
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.CreateModel(
            name="TransportMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_name",
                    models.CharField(
                        default="Transvolt Logistics Private Limited", max_length=200
                    ),
                ),
                ("horse_chassis_no", models.CharField(max_length=50, unique=True)),
                (
                    "horse_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "trolley_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "trolley_chassis_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "Transport Master",
                "verbose_name_plural": "Transport Masters",
                "db_table": "transport_master",
            },
        ),
    ]
