# Generated by Django 4.2.20 on 2025-11-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drivermaster",
            name="employee_name",
        ),
        migrations.RemoveField(
            model_name="horsetrolleyassignment",
            name="driver_name",
        ),
        migrations.AddField(
            model_name="drivermaster",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="drivermaster",
            name="employee_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="drivermaster",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="drivermaster",
            name="phone_encrypted",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drivermaster",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="horsetrolleyassignment",
            name="driver_name_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="horsetrolleyassignment",
            name="assigned_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
