# Generated by Django 5.2.7 on 2025-12-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0003_convert_encrypted_to_plain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horsetrolleyassignment",
            name="driver_code",
        ),
        migrations.RemoveField(
            model_name="horsetrolleyassignment",
            name="driver_name",
        ),
        migrations.RemoveField(
            model_name="horsetrolleyassignment",
            name="horse_number",
        ),
        migrations.RemoveField(
            model_name="horsetrolleyassignment",
            name="trolley_number",
        ),
        migrations.AddField(
            model_name="horsetrolleyassignment",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                db_column="driver_code",
                help_text="Driver assigned to this vehicle",
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="roster.drivermaster",
                to_field="employee_code",
            ),
        ),
        migrations.AddField(
            model_name="horsetrolleyassignment",
            name="horse",
            field=models.ForeignKey(
                blank=True,
                db_column="horse_number",
                help_text="Horse vehicle assigned",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="roster.transportmaster",
                to_field="horse_number",
            ),
        ),
        migrations.AddField(
            model_name="horsetrolleyassignment",
            name="trolley",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional trolley attached to horse (references TransportMaster ID)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trolley_assignments",
                to="roster.transportmaster",
            ),
        ),
    ]
