# Generated by Django 5.2.7 on 2025-12-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0004_remove_horsetrolleyassignment_driver_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horsetrolleyassignment",
            name="trolley",
        ),
        migrations.AddField(
            model_name="horsetrolleyassignment",
            name="trolley_number",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="horsetrolleyassignment",
            name="driver",
            field=models.ForeignKey(
                db_column="driver_code",
                default=111,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="driver_assignments",
                to="roster.drivermaster",
                to_field="employee_code",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="horsetrolleyassignment",
            name="horse",
            field=models.ForeignKey(
                db_column="horse_number",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="horse_assignments",
                to="roster.transportmaster",
                to_field="horse_number",
            ),
        ),
    ]
