# Generated by Django 5.2.7 on 2025-12-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0005_remove_horsetrolleyassignment_trolley_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="horsetrolleyassignment",
            options={
                "ordering": ["-assigned_date"],
                "verbose_name": "Horse Assignment",
                "verbose_name_plural": "Horse Assignments",
            },
        ),
        migrations.RemoveField(
            model_name="horsetrolleyassignment",
            name="trolley_number",
        ),
        migrations.AlterField(
            model_name="horsetrolleyassignment",
            name="assigned_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name="horsetrolleyassignment",
            constraint=models.UniqueConstraint(
                fields=("horse",), name="unique_horse_assignment"
            ),
        ),
    ]
