# Generated by Django 5.2.7 on 2025-12-17 07:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0006_alter_horsetrolleyassignment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horse_number", models.CharField(db_index=True, max_length=50)),
                ("driver_code", models.CharField(db_index=True, max_length=50)),
                ("driver_name", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "previous_driver_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "previous_driver_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Log",
                "verbose_name_plural": "Assignment Logs",
                "db_table": "roster_assignment_log",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["-performed_at"], name="roster_assi_perform_e3f3ff_idx"
                    ),
                    models.Index(
                        fields=["horse_number", "-performed_at"],
                        name="roster_assi_horse_n_f2ecbd_idx",
                    ),
                    models.Index(
                        fields=["driver_code", "-performed_at"],
                        name="roster_assi_driver__178787_idx",
                    ),
                ],
            },
        ),
    ]
