# Generated by Django 4.2.20 on 2025-12-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_assignmentlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='horsetrolleyassignment',
            index=models.Index(fields=['horse', 'assigned_date'], name='idx_horse_date'),
        ),
    ]
