# Generated by Django 4.2.20 on 2025-12-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_horsetrolleyassignment_idx_horse_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsetrolleyassignment',
            name='place',
            field=models.CharField(blank=True, choices=[('DHAR', 'Dhar'), ('DHULE', 'Dhule'), ('JULWANIYA', 'Julwaniya')], help_text='Current place location', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='horsetrolleyassignment',
            name='route',
            field=models.CharField(blank=True, choices=[('DHAR_TO_DHULE', 'Dhar to Dhule'), ('DHULE_TO_DHAR', 'Dhule to Dhar')], help_text='Route direction', max_length=20, null=True),
        ),
    ]
