# Generated by Django 4.2.20 on 2025-12-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_horsetrolleyassignment_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlog',
            name='place',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='assignmentlog',
            name='route',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
