# Generated by Django 4.2.20 on 2025-12-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_assignmentlog_place_assignmentlog_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlog',
            name='lr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horsetrolleyassignment',
            name='lr_number',
            field=models.CharField(blank=True, help_text='LR Number (only applicable when place is Dhar)', max_length=50, null=True),
        ),
    ]
