# Generated by Django 4.2.20 on 2026-01-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_assignmentlog_lr_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsetrolleyassignment',
            name='tonnage',
            field=models.CharField(blank=True, help_text='Tonnage of the Truck', max_length=50, null=True),
        ),
    ]
