# Generated by Django 4.2.20 on 2026-01-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_horsetrolleyassignment_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlog',
            name='tonnage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
