# Generated by Django 4.2.20 on 2026-01-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_assignmentlog_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlog',
            name='previous_lr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assignmentlog',
            name='previous_place',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='assignmentlog',
            name='previous_route',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assignmentlog',
            name='previous_tonnage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
