# Generated by Django 4.2.20 on 2026-01-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0014_assignmentlog_previous_lr_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsetrolleyassignment',
            name='assigned_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
