# Generated by Django 4.2.20 on 2026-01-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_alter_horsetrolleyassignment_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermaster',
            name='ultratech_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
