# Generated by Django 4.2.20 on 2026-01-14 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0016_drivermaster_ultratech_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeboxReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for timebox entry')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(help_text="Driver's phone number", max_length=15)),
                ('vehicle_number', models.CharField(help_text='Vehicle registration number', max_length=50)),
                ('logged_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this was logged')),
                ('logged_by', models.ForeignKey(help_text='User who logged this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timebox_reasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timebox Reason',
                'verbose_name_plural': 'Timebox Reasons',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['-logged_at'], name='roster_time_logged__beebea_idx'), models.Index(fields=['vehicle_number'], name='roster_time_vehicle_d5688e_idx'), models.Index(fields=['driver_phone'], name='roster_time_driver__dd7e51_idx')],
            },
        ),
    ]
